import type { AmbientProfile } from "./ambient-profiles";
import { BENCHES } from "../world/street-props";
import { CASHIER_NPC_POS, COURIER_POS, type Vec3 } from "../world/layout";
import type { NpcRole } from "../interactions/interactables";
import type { AvatarAnimation } from "../avatar/avatar-source";
export interface NpcConfig {
  id: string;
  label: string;
  role: NpcRole;
  persona: string;
  zone: string;
  points: Vec3[];
  speed: number;
  seed: number;
  yaw: number;
  activity: AvatarAnimation;
  carry?: boolean;
  profile?: AmbientProfile;
  desktopOnly?: boolean;
  avatarId?: string;
  seat?: boolean;
  seatBenchId?: string;
}
/** Desktop: 18 ambient + 2 workers. Mobile: 12 ambient + 2 workers. */
export const NPC_CONFIG: NpcConfig[] = [
  {
    id: "npc-shopper-1",
    label: "Bu Sari · Pembeli",
    role: "pembeli",
    zone: "retail",
    persona: "Bu Sari suka membandingkan produk hemat.",
    points: [
      [-3.6, 0, -3],
      [-3.6, 0, -7],
    ],
    speed: 0.65,
    seed: 11,
    yaw: -Math.PI / 2,
    activity: "PickItem",
  },
  {
    id: "npc-shopper-2",
    label: "Mas Dedi · Pembeli",
    role: "pembeli",
    zone: "retail",
    persona: "Mas Dedi mencari minuman dan sembako.",
    points: [
      [3.6, 0, -4],
      [3.6, 0, -9.8],
    ],
    speed: 0.75,
    seed: 31,
    yaw: Math.PI / 2,
    activity: "PickItem",
  },
  {
    id: "npc-shopper-3",
    label: "Mbak Ayu · Promo",
    role: "pembeli",
    zone: "promo",
    persona: "Mbak Ayu sedang mencari promo belanja hari ini.",
    points: [
      [-2.6, 0, 2.3],
      [-4.1, 0, 2.3],
    ],
    speed: 0.55,
    seed: 53,
    yaw: Math.PI,
    activity: "PickItem",
  },
  {
    id: "npc-cashier",
    label: "Mbak Rina · Kasir",
    role: "kasir",
    zone: "cashier",
    persona: "Rina membantu checkout dan pembayaran di Toko Cung.",
    points: [CASHIER_NPC_POS],
    speed: 0,
    seed: 17,
    yaw: 0,
    activity: "Checkout",
  },
  {
    id: "npc-store-staff",
    label: "Nakama · Pramuniaga",
    role: "nakama-gudang",
    zone: "retail",
    persona: "Nakama pramuniaga memeriksa rak dan membantu pelanggan mencari produk.",
    points: [
      [-7.4, 0, -3],
      [-7.4, 0, -9],
    ],
    speed: 0.7,
    seed: 71,
    yaw: Math.PI / 2,
    activity: "PickItem",
    carry: true,
  },
  {
    id: "npc-courier",
    label: "Kurir · Pickup",
    role: "kurir",
    zone: "pickup",
    persona: "Kurir memeriksa manifest dan menunggu paket di pickup.",
    points: [COURIER_POS, [11.7, 0, 9]],
    speed: 0.7,
    seed: 41,
    yaw: Math.PI,
    activity: "UsePhone",
  },
  {
    id: "npc-pedestrian-1",
    profile: "walker",
    label: "Warga Sekitar",
    role: "warga",
    zone: "sidewalk",
    persona: "Warga sekitar sedang berjalan santai di trotoar.",
    points: [
      [-8, 0, 11.7],
      [-5.7, 0, 11.7],
    ],
    speed: 0.5,
    seed: 83,
    yaw: Math.PI,
    activity: "Idle",
  },
  {
    id: "npc-pedestrian-2",
    profile: "observer",
    label: "Pak Budi · Warga",
    role: "warga",
    zone: "sidewalk",
    persona: "Pak Budi beristirahat dekat bangku dan senang bercerita tentang lingkungan.",
    points: [[5.8, 0, 11.6]],
    speed: 0,
    seed: 97,
    yaw: -Math.PI / 2,
    activity: "UsePhone",
  },
  {
    id: "npc-resident-left",
    label: "Bu Wati · Warga",
    role: "warga",
    zone: "sidewalk-left",
    persona: "Bu Wati berjalan santai di depan rumah tetangga.",
    profile: "walker",
    points: [
      [-34.2, 0, -15],
      [-34.2, 0, -9],
    ],
    speed: 0.65,
    seed: 109,
    yaw: 0,
    activity: "Idle",
    avatarId: "npc-shopper-1",
  },
  {
    id: "npc-resident-sitter",
    label: "Pak Hadi · Warga",
    role: "warga",
    zone: "bench",
    persona: "Pak Hadi beristirahat di bangku trotoar.",
    profile: "sitter",
    seat: true,
    seatBenchId: "bench-road-east",
    points: [BENCHES.find((b) => b.id === "bench-road-east")!.position],
    speed: 0,
    seed: 127,
    yaw: Math.PI / 2,
    activity: "Sit",
    avatarId: "npc-owner",
  },
  {
    id: "npc-resident-chat-a",
    label: "Mbak Nita · Warga",
    role: "warga",
    zone: "sidewalk-right",
    persona: "Nita berbincang dengan tetangganya tentang belanja hari ini.",
    profile: "chat-pair",
    desktopOnly: true,
    points: [[26.2, 0, 0]],
    speed: 0,
    seed: 139,
    yaw: 0,
    activity: "Talk",
    avatarId: "npc-shopper-3",
  },
  {
    id: "npc-resident-chat-b",
    label: "Mas Arif · Warga",
    role: "warga",
    zone: "sidewalk-right",
    persona: "Arif berbincang santai dengan Nita di tepi trotoar.",
    profile: "chat-pair",
    desktopOnly: true,
    points: [[26.2, 0, 1.5]],
    speed: 0,
    seed: 151,
    yaw: Math.PI,
    activity: "Talk",
    avatarId: "npc-shopper-2",
  },
  {
    id: "npc-resident-crossing",
    label: "Bu Rini · Warga",
    role: "warga",
    zone: "crosswalk",
    persona: "Bu Rini menunggu jalan aman sebelum menyeberang ke pertokoan.",
    profile: "crossing-pedestrian",
    points: [
      [-23.6, 0, 15.5],
      [-23.6, 0, 24.4],
    ],
    speed: 1.2,
    seed: 167,
    yaw: Math.PI,
    activity: "Idle",
    avatarId: "npc-pedestrian-1",
  },
  {
    id: "npc-resident-loading",
    label: "Pak Joko · Warga",
    role: "warga",
    zone: "service-walk",
    persona: "Pak Joko menunggu kabar pesanan di jalur pejalan kaki samping gudang.",
    profile: "shop-visitor",
    points: [
      [9.9, 0, -19.5],
      [9.9, 0, -21.8],
    ],
    speed: 0.5,
    seed: 181,
    yaw: -Math.PI / 2,
    activity: "UsePhone",
    avatarId: "npc-pedestrian-2",
  },
  {
    id: "npc-visitor-west",
    label: "Bu Lina · Pengunjung",
    role: "pembeli",
    zone: "neighbor-storefront",
    desktopOnly: true,
    persona: "Bu Lina melihat toko tetangga sebelum melanjutkan belanja.",
    profile: "shop-visitor",
    points: [
      [-25.8, 0, -7],
      [-25.8, 0, -4],
    ],
    speed: 0.55,
    seed: 193,
    yaw: Math.PI / 2,
    activity: "Idle",
    avatarId: "npc-shopper-1",
  },
  {
    id: "npc-visitor-south",
    label: "Mas Rudi · Pengunjung",
    role: "pembeli",
    zone: "neighbor-storefront",
    desktopOnly: true,
    persona: "Rudi berjalan di depan pertokoan mitra.",
    profile: "shop-visitor",
    points: [
      [6, 0, 24.2],
      [9, 0, 24.2],
    ],
    speed: 0.6,
    seed: 211,
    yaw: 0,
    activity: "UsePhone",
    avatarId: "npc-shopper-2",
  },
  {
    id: "npc-visitor-window",
    label: "Mbak Dewi · Pengunjung",
    role: "pembeli",
    zone: "storefront",
    desktopOnly: true,
    persona: "Dewi melihat pilihan produk dari sisi etalase toko.",
    profile: "observer",
    points: [[-7.4, 0, 3.9]],
    speed: 0,
    seed: 223,
    yaw: Math.PI,
    activity: "Idle",
    avatarId: "npc-shopper-3",
  },
  {
    id: "npc-courier-waiting",
    label: "Kurir · Menunggu",
    role: "kurir",
    zone: "pickup-surroundings",
    desktopOnly: true,
    persona: "Kurir menunggu pesanan sambil menjaga jalur pickup tetap kosong.",
    profile: "observer",
    points: [[18, 0, 7]],
    speed: 0,
    seed: 239,
    yaw: -Math.PI / 2,
    activity: "UsePhone",
    avatarId: "npc-courier",
  },
];
export const WORKER_IDS = ["npc-nakama-warehouse", "npc-nakama-packing"] as const;

export function populationForQuality(lowQuality: boolean) {
  return NPC_CONFIG.filter((npc) => !lowQuality || !npc.desktopOnly);
}
